// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2xI-AsRhcxS5NbNMirtYmReHhpfWuj4E',
    appId: '1:1047671029557:web:71a2860a70f1bcbb86967c',
    messagingSenderId: '1047671029557',
    projectId: 'sow-good',
    authDomain: 'sow-good.firebaseapp.com',
    storageBucket: 'sow-good.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVVOQWjcbgsC5lH8aRSujdwkjRPMSlfJs',
    appId: '1:1047671029557:android:221f8bb56475cf3386967c',
    messagingSenderId: '1047671029557',
    projectId: 'sow-good',
    storageBucket: 'sow-good.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwfLKFEVDmyno1LgfHFjfMPVnCLkRyo1M',
    appId: '1:1047671029557:ios:f064c763a792045686967c',
    messagingSenderId: '1047671029557',
    projectId: 'sow-good',
    storageBucket: 'sow-good.appspot.com',
    iosClientId: '1047671029557-rva0miq0in56p432vtjmg0kbrk71m5qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sowGood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwfLKFEVDmyno1LgfHFjfMPVnCLkRyo1M',
    appId: '1:1047671029557:ios:f064c763a792045686967c',
    messagingSenderId: '1047671029557',
    projectId: 'sow-good',
    storageBucket: 'sow-good.appspot.com',
    iosClientId: '1047671029557-rva0miq0in56p432vtjmg0kbrk71m5qj.apps.googleusercontent.com',
    iosBundleId: 'com.example.sowGood',
  );
}
